### ISSUE TITLE
[Bug] Error when using Latent Mirror due to mismatch Tensor size

### ISSUE THREAD

**Issue by Nandaka** [dfaker/SD-latent-mirroring#1]
**Mode: Alternate Step**
![image](https://user-images.githubusercontent.com/836867/200977866-30e79423-707a-4ec4-8bca-20c5e0973864.png)

Error message: RuntimeError: The expanded size of the tensor (64) must match the existing size (96) at non-singleton dimension 3.

log:
```
 25%|█████████████████████████▊                                                                             | 7/28 [00:12<00:36,  1.74s/it]Error executing callback cfg_denoiser_callback for C:\stable-diffusion\stable-diffusion-webui\extensions\SD-latent-mirroring\scripts\latent_mirroring.py
Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 135, in cfg_denoiser_callback
    c.callback(params)
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\SD-latent-mirroring\scripts\latent_mirroring.py", line 34, in denoise_callback
    params.x[:, :, :, :] = torch.rot90(params.x, dims=[2, 3])
RuntimeError: The expanded size of the tensor (64) must match the existing size (96) at non-singleton dimension 3.  Target sizes: [2, 4, 96, 64].  Tensor sizes: [2, 4, 64, 96]
```

**Mode: Blend Average**
![image](https://user-images.githubusercontent.com/836867/200978030-27c39b4b-ea8f-4b4d-bc27-87f0e4db666b.png)

Error Message: RuntimeError: The size of tensor a (128) must match the size of tensor b (96) at non-singleton dimension 3

Log:
```
 25%|█████████████████████████▊                                                                             | 7/28 [00:30<01:30,  4.30s/it]Error executing callback cfg_denoiser_callback for C:\stable-diffusion\stable-diffusion-webui\extensions\SD-latent-mirroring\scripts\latent_mirroring.py
Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\modules\script_callbacks.py", line 135, in cfg_denoiser_callback
    c.callback(params)
  File "C:\stable-diffusion\stable-diffusion-webui\extensions\SD-latent-mirroring\scripts\latent_mirroring.py", line 48, in denoise_callback
    params.x[:, :, :, :] = (torch.rot90(params.x, dims=[2, 3]) + params.x)/2
RuntimeError: The size of tensor a (128) must match the size of tensor b (96) at non-singleton dimension 3
```

Model used
![image](https://user-images.githubusercontent.com/836867/200978183-6b28bace-b14d-4efa-9932-f6b4df363ec9.png)

**Comment by Nandaka** [comment]
Is it due to the aspect ratio is not 1:1 for 90 degree rotation?

**Comment by dfaker** [comment]
Yes that's correct, the 90 degree rotation needs a square aspect ratio to work.

**Comment by Nandaka** [comment]
Is it possible to return readable error message, instead just throwing RuntimeError, as the default error message isn't that readable.

Thanks :D

**Comment by dfaker** [comment]
Updated now.
